spring:

  main:
    allow-circular-references: true

  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/tableplan_project?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      maximum-pool-size: 20
      driver-class-name: org.postgresql.Driver
    username: dev
    password: dev
    url: "jdbc:postgresql://localhost:5432/tableplan_project?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
      #    locations: classpath:/db
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: public
    out-of-order: true
    ignore-migration-patterns: '*:ignored'

  jpa:
    show-sql: true
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: false
        jdbc:
          batch_size: 5
        generate_statistics: true

  data:
    rest:
      default-page-size: 1

  mail:

    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

    host: smtp.gmail.com
    port: 587
    username: tableplan.info@gmail.com
    password: fclb ljee gxgq hjyn
    default-encoding: UTF-8

  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8

---

logging:
  level:
    org.hibernate:
      engine.jdbc.batch.internal.BatchingBatch: DEBUG
    root: info

---

#crud_limit_offset:
#  default_find_all_limit: 20
#  default_find_all_offset: 0
#  default-page-size-by-month: 30

---

year.current: 2023
year.next: 2024

---

response.entity.name:
  restaurants: "restaurants"
  reservations: "reservations"

---

email:

  subject:
    reservation:
      confirmed: "Reservation is confirmed"
      not-confirmed: "Reservation is not confirmed"
      cancelled: "Reservation is cancelled"

  template-path:
    reservation:
      confirmed: "email_confirmation.html"
      not-confirmed: "email_non_confirmation.html"
      cancelled: "email_annulation.html"

  pattern:
    date: "eeee dd MMMM"

  address-details:
    from: "tableplan.info@gmail.com"
    to: "zzgurezz@gmail.com"
    recipient-email: "zzgurezz@gmail.com"
    language: "En"

---