CREATE SEQUENCE IF NOT EXISTS enabled_generated_type_sequence
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE restaurants
(
    restaurant_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_name           VARCHAR(100) NOT NULL,
    contact_email             VARCHAR(200) NOT NULL,
    phone                     VARCHAR(20),
    address                   VARCHAR(200),
    postal_code               VARCHAR(10),
    city                      VARCHAR(50),
    country                   VARCHAR(30),
    website                   VARCHAR(200),
    restaurant_language       VARCHAR(5),
    restaurant_timezone       VARCHAR(50),
    image_url                 VARCHAR(500),
    logo_url                  VARCHAR(500),
    created                   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed                   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted                BOOLEAN NOT NULL DEFAULT FALSE,
    auth_email                VARCHAR(200),
    auth_password             VARCHAR(255),
    default_timeslot_capacity INTEGER NOT NULL DEFAULT 20,

    CONSTRAINT restaurants_default_capacity_check
        CHECK (default_timeslot_capacity > 0)
);

CREATE TABLE reservations
(
    reservation_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pnr             VARCHAR(6) NOT NULL,
    restaurant_id   BIGINT NOT NULL,
    local_date      DATE NOT NULL,
    local_time      TIME NOT NULL,
    party_size      INTEGER NOT NULL,
    guest_full_name VARCHAR(200) NOT NULL,
    guest_email     VARCHAR(200) NOT NULL,
    guest_phone     VARCHAR(20) NOT NULL,
    guest_note      VARCHAR(300),
    guest_language  VARCHAR(5) NOT NULL DEFAULT 'en',
    status          VARCHAR(15) NOT NULL DEFAULT 'UNREAD',
    created         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT reservations_restaurant_fk
        FOREIGN KEY (restaurant_id)
            REFERENCES restaurants (restaurant_id),
    CONSTRAINT reservations_party_size_check
        CHECK (party_size > 0),
    CONSTRAINT reservations_status_check
        CHECK (status IN ('UNREAD', 'NOT_CONFIRMED', 'CONFIRMED', 'PLANNED', 'WAITING_LIST', 'CANCELLED', 'OTHER'))
);

COMMENT ON COLUMN reservations.pnr IS 'Personal reservation number';
COMMENT ON COLUMN reservations.guest_note IS 'Guest special requests';

CREATE TABLE calendar_days
(
    calendar_day_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_date      DATE NOT NULL,
    restaurant_id   BIGINT NOT NULL,
    is_open         BOOLEAN NOT NULL DEFAULT TRUE,
    created         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT calendar_days_restaurant_fk
        FOREIGN KEY (restaurant_id)
            REFERENCES restaurants (restaurant_id),
    CONSTRAINT calendar_days_restaurant_date_uk
        UNIQUE (restaurant_id, local_date)
);

CREATE TABLE timeslots
(
    timeslot_id           BIGINT PRIMARY KEY
        DEFAULT nextval('enabled_generated_type_sequence'),
    calendar_day_id       BIGINT NOT NULL,
    local_time            TIME NOT NULL,
    is_available          BOOLEAN NOT NULL DEFAULT TRUE,
    current_slot_capacity INTEGER NOT NULL DEFAULT 0,
    max_slot_capacity     INTEGER NOT NULL,
    created               TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed               TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted            BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT timeslots_calendar_day_fk
        FOREIGN KEY (calendar_day_id)
            REFERENCES calendar_days (calendar_day_id)
            ON DELETE CASCADE,
    CONSTRAINT timeslots_calendar_day_time_uk
        UNIQUE (calendar_day_id, local_time),
    CONSTRAINT timeslots_capacity_check
        CHECK (
            current_slot_capacity >= 0
            AND max_slot_capacity >= 0
            AND current_slot_capacity <= max_slot_capacity
        )
);

CREATE TABLE default_week_days
(
    default_week_day_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id       BIGINT NOT NULL,
    day_of_week         INTEGER NOT NULL,
    is_open             BOOLEAN NOT NULL DEFAULT TRUE,
    created             TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed             TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT default_week_days_restaurant_fk
        FOREIGN KEY (restaurant_id)
            REFERENCES restaurants (restaurant_id)
            ON DELETE CASCADE,
    CONSTRAINT default_week_days_restaurant_day_uk
        UNIQUE (restaurant_id, day_of_week),
    CONSTRAINT default_week_days_day_check
        CHECK (day_of_week BETWEEN 0 AND 6)
);

CREATE TABLE default_times
(
    default_time_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_time      TIME NOT NULL,

    CONSTRAINT default_times_local_time_uk
        UNIQUE (local_time)
);

CREATE TABLE l_default_week_days_times
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    default_week_day_id BIGINT NOT NULL,
    default_time_id     BIGINT NOT NULL,

    CONSTRAINT default_week_days_times_week_day_fk
        FOREIGN KEY (default_week_day_id)
            REFERENCES default_week_days (default_week_day_id)
            ON DELETE CASCADE,
    CONSTRAINT default_week_days_times_time_fk
        FOREIGN KEY (default_time_id)
            REFERENCES default_times (default_time_id)
            ON DELETE CASCADE,
    CONSTRAINT default_week_days_times_uk
        UNIQUE (default_week_day_id, default_time_id)
);
